properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cluster:
    type: string
    x-google-marketplace:
      type: CLUSTER
  cluster-zone:
    type: string
    default: us-east1-b
    description: The zone the cluster is. Why do we need this?
required:
- name
- namespace
- cluster
- cluster-zone