properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cluster:
    type: string
    x-google-marketplace:
      type: CLUSTER
required:
- name
- namespace
- cluster