properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  operatorServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole  
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin  
required:
- name
- namespace
- operatorServiceAccount